plugins {
    id 'java-library'
}

bootJar { enabled = false }
jar { enabled = true }

dependencies {
    api 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.springframework.boot:spring-boot-starter-data-jpa'
    compileOnly 'org.springframework.boot:spring-boot-starter-security'
    compileOnly 'io.jsonwebtoken:jjwt-api:0.12.6'
}